name: place_archive
description: 장소 기억 아카이브
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.18.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0
  google_fonts: ^6.2.1
  geolocator: ^13.0.2
  google_maps_flutter: ^2.9.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
