// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjG1fbZHpVNQVqnynLVhq62v_SpALWolw',
    appId: '1:342025363300:android:19fd8c132587b669692471',
    messagingSenderId: '342025363300',
    projectId: 'place-c46c0',
    storageBucket: 'place-c46c0.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjG1fbZHpVNQVqnynLVhq62v_SpALWolw',
    appId: '1:342025363300:web:f7fc019ee16249b3692471',
    messagingSenderId: '342025363300',
    projectId: 'place-c46c0',
    authDomain: 'place-c46c0.firebaseapp.com',
    storageBucket: 'place-c46c0.firebasestorage.app',
  );
}
